// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateJWTSecret():Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetDatabaseStatus():Promise<main.DatabaseStatus>;

export function GetServiceStatus():Promise<boolean>;

export function InitDatabase(arg1:string,arg2:string):Promise<string>;

export function ProvisionInitialAdmin(arg1:string,arg2:string):Promise<string>;

export function ResetAdminPassword(arg1:string,arg2:string):Promise<string>;

export function SaveAppName(arg1:string):Promise<void>;

export function SaveDatabaseConfig(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveJWTSecret(arg1:string):Promise<void>;

export function SaveWebPort(arg1:number):Promise<void>;

export function StartService():Promise<string>;

export function StopService():Promise<string>;

export function TestConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function UpgradeDatabase():Promise<string>;
