// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateJWTSecret() {
  return window['go']['main']['App']['GenerateJWTSecret']();
}

export function GetBuildVersion() {
  return window['go']['main']['App']['GetBuildVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDatabaseStatus() {
  return window['go']['main']['App']['GetDatabaseStatus']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function InitDatabase(arg1, arg2) {
  return window['go']['main']['App']['InitDatabase'](arg1, arg2);
}

export function ProvisionInitialAdmin(arg1, arg2) {
  return window['go']['main']['App']['ProvisionInitialAdmin'](arg1, arg2);
}

export function ResetAdminPassword(arg1, arg2) {
  return window['go']['main']['App']['ResetAdminPassword'](arg1, arg2);
}

export function SaveAppName(arg1) {
  return window['go']['main']['App']['SaveAppName'](arg1);
}

export function SaveDatabaseConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveDatabaseConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveJWTSecret(arg1) {
  return window['go']['main']['App']['SaveJWTSecret'](arg1);
}

export function SaveWebPort(arg1) {
  return window['go']['main']['App']['SaveWebPort'](arg1);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function TestConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function UpgradeDatabase() {
  return window['go']['main']['App']['UpgradeDatabase']();
}
